### ISSUE TITLE
Cant join from non premium account

### ISSUE THREAD

**Issue by QuantumV2** [RhysB/Project-Poseidon#34]
how do i fix that

**Comment by RhysB** [comment]
Is the server in online mode? if so toggle the setting in server.properties. Otherwise, you might have the _allow-graceful-uuids_ setting in poseidon.yml set to false which is blocking non registered usernames from connecting.

**Comment by moderatorman** [comment]
The obvious solution would be to buy the game.

**Comment by QuantumV2** [comment]
> Is the server in online mode? if so toggle the setting in server.properties. Otherwise, you might have the _allow-graceful-uuids_ setting in poseidon.yml set to false which is blocking non registered usernames from connecting.

i did that, thats like no effect

**Comment by RhysB** [comment]
What message are clients receiving when connecting?

**Comment by QuantumV2** [comment]
> What message are clients receiving when connecting?

Sorry, we can't connect to Mojang currently, please try again later

**Comment by QuantumV2** [comment]
> > What message are clients receiving when connecting?
> 
> Sorry, we can't connect to Mojang currently, please try again later

settings:
    release2beta:
        enable-ip-pass-through: false
        proxy-ip: 127.0.0.1
    check-username-validity:
        enabled: false
        info: If enabled, verifies the validity of a usernames of cracked players.
        regex: '[a-zA-Z0-9_?]*'
        max-length: 16
        min-length: 3
    support:
        modloader:
            enable: false
            info: EXPERIMENTAL support for ModloaderMP.
    statistics:
        key: ********************************************
        enabled: true
    allow-graceful-uuids: true
    delete-duplicate-uuids: false
    save-playerdata-by-uuid: true
    per-day-logfile: false
    fetch-uuids-from: https://api.mojang.com/profiles/minecraft
    enable-watchdog: true
    remove-join-leave-debug: true
    enable-tpc-nodelay: false
world-settings:
    optimized-explosions: false
    randomize-spawn: true
    teleport-to-highest-safe-block: true
    use-modern-fence-bounding-boxes: true
config-version: 2

**Comment by RhysB** [comment]
Weird, does it provide any debug in the console? Is the machine connected to the internet ? does it work if you change `use-get-for-uuids` to true?

**Comment by QuantumV2** [comment]
> Weird, does it provide any debug in the console? Is the machine connected to the internet ? does it work if you change `use-get-for-uuids` to true?

i dont see use-get-for-uuids in the yml file

**Comment by QuantumV2** [comment]
> Weird, does it provide any debug in the console? Is the machine connected to the internet ? does it work if you change `use-get-for-uuids` to true?

nevermind i fixed this by rebuilding poseidon

**Comment by moderatorman** [comment]
> 
> 
> > Weird, does it provide any debug in the console? Is the machine connected to the internet ? does it work if you change `use-get-for-uuids` to true?
> 
> nevermind i fixed this by rebuilding poseidon

Has your issue been resolved?

**Comment by QuantumV2** [comment]
> > > Weird, does it provide any debug in the console? Is the machine connected to the internet ? does it work if you change `use-get-for-uuids` to true?
> > 
> > 
> > nevermind i fixed this by rebuilding poseidon
> 
> Has your issue been resolved?

sadly no, after i did this after some time it started the same problem again

**Comment by RhysB** [comment]
Please reopen a new issue if this is still occurring. As far as I am aware this isn't an issue.
