### ISSUE TITLE
Use lombok

### ISSUE THREAD

**Issue by CodeKid0** [RhysB/Project-Poseidon#52]
Using lombok for getters and setters would make the code cleaner.

**Comment by Chew** [comment]
Yeah, but then you're using lombok. Not worth it

**Comment by RhysB** [comment]
Reposting my answer from the OSM Discord

I have considered adding Lombok to Poseidon and some of my other projects before, but I am not a big fan of it. Here are a few of the reasons I am not the biggest fan of adding it:
-    Adding it to Poseidon requires anyone who developers on it to install the corresponding plugin for their IDE.
-    Projects that use Lombok often fail to respect encapsulation.
-    It can sometimes make code bases more annoying to read or debug, especially when code using Lombok is mixed with code that isn’t. Not such a big deal for Poseidon, but it also affects the usefulness of JavaDocs.
-    Poseidon already has a stable codebase and is in a sustainment phase. So adding Lombok now wouldn’t provide a massive advantage as very little of the code would ever use Lombok.
-    Modern IDEs already provide easy ways to generate and manage getters and setters without the reliance on a third party library.

I am not saying Lombok is a bad addition to a code base, but it doesn’t provide enough value in Poseidon compared to the disadvantages in my opinion.
