### ISSUE TITLE
Logging out in the Nether causes the whole game to crash and makes the server inaccessible

### ISSUE THREAD

**Issue by ThatAlecs** [RhysB/Project-Poseidon#70]
Hello everyone,
I run a server on Beta 1.1_02 using Poseidon and this error happens when you log out in the Nether and then log in the server again:

![image](https://github.com/RhysB/Project-Poseidon/assets/41908942/4747fbab-1018-4e7d-a1a1-eabeff586329)

This absolutely prevents the player from logging in the server **until the server owner/admin deletes their player data file, which resets all their data and progress on the server**
When you try to log in the server while in the Nether, Minecraft will hang and then crash after a few minutes.

The steps to reproduce this bug are very simple:

1. Run a Beta 1.1_02 server using Project Poseidon
2. Get to the Nether
3. Log out
4. Try to log back in

**Comment by ThatAlecs** [comment]
Forgot to say the server runs on the latest version of Poseidon

**Comment by CodeKid0** [comment]
You're not running poseidon, but UberBukkit. Post an issue there: https://github.com/Moresteck/Project-Poseidon-Uberbukkit

**Comment by ThatAlecs** [comment]
Sorry for the misunderstanding! I downloaded it from Betacraft and didn't really know the difference.
