### ISSUE TITLE
GetUUIDFetcher Doesn't Honor settings.fetch-uuids-from

### ISSUE THREAD

**Issue by MaximilianEmel** [RhysB/Project-Poseidon#72]
When setting `use-get-for-uuids:` to `true` in `poseidon.yml`, it stops honoring the `fetch-uuids-from:` setting, and instead uses a hardcoded `https://api.mojang.com/users/profiles/minecraft/`.

**Comment by RhysB** [comment]
Long story short, use-get-for-uuids was added in a rush when Mojang had a bug with POST not working for some reason around two years ago and was never fully flushed out.

For anyone working on this issue, it is likely good to allow the user to specify and POST and GET URL in the config alongside which one is going to be used.
