### ISSUE TITLE
Sorry, we can't connect to Mojang currently, please try again later

### ISSUE THREAD

**Issue by DearFox** [RhysB/Project-Poseidon#75]
My server is set to online-mode=false (otherwise the game (client) just freezes and has to be stopped by force).
I tried disabling all settings related to UUID and all that, but it didn't give any result.

My config file: [poseidon.yml.txt](https://github.com/RhysB/Project-Poseidon/files/13366380/poseidon.yml.txt)
I use project-poseidon-1.1.8.jar
My client is a vanilla client b1.7.3 with EarsMod (since it +- fixes skins)

When I try to connect to the server via ":25565" I get an error "Sorry, we can't connect to Mojang currently, please try again later"

The link "https://api.mojang.com/profiles/minecraft" does not work if you try to open it in a browser.

**Comment by RhysB** [comment]
You will need to disable online mode if you don't have a mod that fixes authentication in the client.

Otherwise, try disabling use-get-for-uuids in your poseidon.yml and see if you still have issues.

You shouldn't really be disabling settings for UUIDs in 2023 due to username changes.

Please respond if that works for you!

**Comment by DearFox** [comment]
I get an error in the console:

```
23:13:39 [INFO] Mojang failed contact for user Usen_Name:

23:13:39 [SEVERE] java.net.SocketException: Connection reset

23:13:39 [SEVERE]       at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)

23:13:39 [SEVERE]       at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)

23:13:39 [SEVERE]       at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)

23:13:39 [SEVERE]       at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)

23:13:39 [SEVERE]       at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)

23:13:39 [SEVERE]       at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)

23:13:39 [SEVERE]       at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)

23:13:39 [SEVERE]       at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)

23:13:39 [SEVERE]       at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)

23:13:39 [SEVERE]       at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)

23:13:39 [SEVERE]       at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)

23:13:39 [SEVERE]       at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)

23:13:39 [SEVERE]       at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:580)

23:13:39 [SEVERE]       at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)

23:13:39 [SEVERE]       at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1430)

23:13:39 [SEVERE]       at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1401)

23:13:39 [SEVERE]       at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)

23:13:39 [SEVERE]       at com.legacyminecraft.poseidon.util.UUIDFetcher.writeBody(UUIDFetcher.java:56)

23:13:39 [SEVERE]       at com.legacyminecraft.poseidon.util.UUIDFetcher.call(UUIDFetcher.java:39)

23:13:39 [SEVERE]       at com.legacyminecraft.poseidon.util.UUIDFetcher.getUUIDOf(UUIDFetcher.java:95)

23:13:39 [SEVERE]       at com.legacyminecraft.poseidon.uuid.ThreadUUIDFetcher.postMethod(ThreadUUIDFetcher.java:68)

23:13:39 [SEVERE]       at com.legacyminecraft.poseidon.uuid.ThreadUUIDFetcher.run(ThreadUUIDFetcher.java:34)

23:13:39 [INFO] Disconnecting Usen_Name [/127.0.0.1:51429]: зcSorry, we can't connect to Mojang currently, please try again later

**Comment by DearFox** [comment]
Is the server trying to contact the Mojang servers to get the user's UUID?
 If so, and if this cannot be turned off, then most likely this will always cause a problem for me, since Mojang servers are not available for me.
 Lately I've been having problems with the mojang api, or my ISP decided to block it, or mojang decided to block me, I don't know.
 
If all this makes sense, and my mistake is related to this, the solution may be https://corsjang.b-cdn.net/
  So for example, I had problems with EarsMod, but the author of the mod made a version of the mod using this.. thing (I don’t know what it’s called correctly, a proxy for the api or something like that) and now I have no problems loading my skins.

**Comment by Andrmist** [comment]
I have same problem, but I give you some logs:
```
20:56:43 [INFO] Mojang failed contact for user REDACTED:
20:56:43 [SEVERE] java.io.FileNotFoundException: https://api.mojang.com/profiles/minecraft
20:56:43 [SEVERE]       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1893)
20:56:43 [SEVERE]       at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
20:56:43 [SEVERE]       at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
20:56:43 [SEVERE]       at com.legacyminecraft.poseidon.util.UUIDFetcher.call(UUIDFetcher.java:40)
20:56:43 [SEVERE]       at com.legacyminecraft.poseidon.util.UUIDFetcher.getUUIDOf(UUIDFetcher.java:95)
20:56:43 [SEVERE]       at com.legacyminecraft.poseidon.uuid.ThreadUUIDFetcher.postMethod(ThreadUUIDFetcher.java:68)
20:56:43 [SEVERE]       at com.legacyminecraft.poseidon.uuid.ThreadUUIDFetcher.run(ThreadUUIDFetcher.java:34)
```
If I understand, this is because the status code is 404 when offline user, so Java throws error. Maybe we should add [here](https://github.com/RhysB/Project-Poseidon/blob/a9f87403d15e3dfefd0f7e769eff3a1dd7f5db50/src/main/java/com/legacyminecraft/poseidon/util/UUIDFetcher.java#L40C7-L40C7) try-catch for it?

**Comment by Andrmist** [comment]
Maybe it'll fix the problem: #79

**Comment by RhysB** [comment]
@DearFox Have you confirmed that the newest version alongside enabling Fetch UUID By Get has resolved this?

**Comment by RhysB** [comment]
Assuming resolved

**Comment by D3nn11s** [comment]
`17:30:35 [INFO] [Poseidon] Mojang failed contact for user -:
17:30:35 [INFO] [Poseidon] If this issue persists, please utilize the GET method. Mojang's API frequently has issues with POST requests.
17:30:35 [INFO] [Poseidon] You can do this by changing settings.uuid-fetcher.method.value to GET in the config
17:30:35 [SEVERE] java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.minecraftservices.com/minecraft/profile/lookup/bulk/byname
17:30:35 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
17:30:35 [SEVERE] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1517)
17:30:35 [SEVERE] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
17:30:35 [SEVERE] 	at com.legacyminecraft.poseidon.util.UUIDFetcher.call(UUIDFetcher.java:40)
17:30:35 [SEVERE] 	at com.legacyminecraft.poseidon.util.UUIDFetcher.getUUIDOf(UUIDFetcher.java:95)
17:30:35 [SEVERE] 	at com.legacyminecraft.poseidon.uuid.ThreadUUIDFetcher.postMethod(ThreadUUIDFetcher.java:82)
17:30:35 [SEVERE] 	at com.legacyminecraft.poseidon.uuid.ThreadUUIDFetcher.run(ThreadUUIDFetcher.java:34)
17:30:35 [INFO] Disconnecting - [/-]: ?cSorry, we can't connect to Mojang currently, please try again later`

even tho the server is set to online-mode false
