### ISSUE TITLE
Use latest.log for the current log file

### ISSUE THREAD

**Issue by Krafting** [RhysB/Project-Poseidon#81]
With this option : 
```
    per-day-logfile: true
```

It generate a file with the `year-month-day.log` format. It should generate a file latest.log and everyday rotate this file instead.

Why ? 

Dashboards like Crafty Controller or others, use a filename to display latest logs (in addition to the live terminal of the server), in newer version of Minecraft/Spigot it is `logs/latest.log`, however, here, every day we would need to change the path of the latest log file in Crafty, which is quite annoying when you need to get the logs. 

I don't have many log files for now, but it might be a pain in the futur to get the current one...

I hope I've been clear enough in my explainations

Thanks for maintaining such project, it is awesome!

**Comment by RhysB** [comment]
Greeting,

More than happy to mimic the modern system for log management, especially if some control panels rely on it.

It is a low priority for me to work on, although, I would be more than willing to accept pull requests regarding this issue.

**Comment by joshuareisbord** [comment]
> With this option : 
> 
> ```
> 
>     per-day-logfile: true
> 
> ```
> 
> 
> 
> It generate a file with the `year-month-day.log` format. It should generate a file latest.log and everyday rotate this file instead.
> 
> 
> 
> Why ? 
> 
> 
> 
> Dashboards like Crafty Controller or others, use a filename to display latest logs (in addition to the live terminal of the server), in newer version of Minecraft/Spigot it is `logs/latest.log`, however, here, every day we would need to change the path of the latest log file in Crafty, which is quite annoying when you need to get the logs. 
> 
> 
> 
> I don't have many log files for now, but it might be a pain in the futur to get the current one...
> 
> 
> 
> I hope I've been clear enough in my explainations
> 
> 
> 
> Thanks for maintaining such project, it is awesome!

PR for this was merged. Should be all good :)

**Comment by Krafting** [comment]
> > With this option :
> > ```
> > 
> >     per-day-logfile: true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It generate a file with the `year-month-day.log` format. It should generate a file latest.log and everyday rotate this file instead.
> > Why ?
> > Dashboards like Crafty Controller or others, use a filename to display latest logs (in addition to the live terminal of the server), in newer version of Minecraft/Spigot it is `logs/latest.log`, however, here, every day we would need to change the path of the latest log file in Crafty, which is quite annoying when you need to get the logs.
> > I don't have many log files for now, but it might be a pain in the futur to get the current one...
> > I hope I've been clear enough in my explainations
> > Thanks for maintaining such project, it is awesome!
> 
> PR for this was merged. Should be all good :)

I've just tried it, and it seems to be all good after enabling the new option in the config file!

Thank you for your work ! :)
