### ISSUE TITLE
Creepers not dropping music discs when killed by skeletons

### ISSUE THREAD

**Issue by DianaIsntHere** [RhysB/Project-Poseidon#87]
As the title says, creepers do not drop music discs when killed by a skeleton. This behavior has also been observed on a CraftBukkit server, so it might be a bug carried over from CraftBukkit. I tested this on Poseidon, CraftBukkit, and vanilla servers. Vanilla dropped music discs but the other two didn't.

**Comment by AleksandarHaralanov** [comment]
This issue can be closed as a fix for it was merged.

**Comment by moderatorman** [comment]
Fixed in https://github.com/RhysB/Project-Poseidon/pull/104
